apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
  namespace: chat
data:
  DB_HOST: chat-postgres
  DB_PORT: "5432"
  DB_NAME: chat-aio
  DB_USER: postgres
  MINIO_ENDPOINT: chat-minio
  MINIO_PORT: "9000"
  MINIO_USE_SSL: "false"
  MINIO_BUCKET: uploads
